let Champions = {
    id: 0,
    seguidores: 1300000,
    autor: "UEFA - Champions League",
    nome: "Champions League",
    descricao: "A Liga dos Campeões da UEFA é uma competição anual de futebol em nível continental, organizada pela União das Associações Europeias de Futebol e disputada por clubes da Europa.",
    visibilidade: "Publico",
    esporte: "CHAMPIONS",
    tipoCampeonato: "Eliminatorias",
    placarConfig: {
        qntSets: 1,
    },
    confrontos: [
        {
            status: "Encerrado",
            ladoA: "BarSemLona",
            ladoB: "PSG",
            data: "08/03/2017",
            hora: "16:45",
            lugar: "Spotify Camp Nou",
            resultadoA: "6",
            resultadoB: "1",
        },
        {
            status: "Encerrado",
            ladoA: "Man. City",
            ladoB: "RB Leipzig",
            data: "14/03/2023",
            hora: "17:00",
            lugar: "Etihad Stadium",
            resultadoA: "7",
            resultadoB: "0",
        },
        {
            status: "Encerrado",
            ladoA: "Man. City",
            ladoB: "RB Leipzig",
            data: "14/03/2023",
            hora: "17:00",
            lugar: "Etihad Stadium",
            resultadoA: "7",
            resultadoB: "0",
        },
        {
            status: "Encerrado",
            ladoA: "Real Madrid",
            ladoB: "Liverpool",
            data: "15/03/2023",
            hora: "17:00",
            lugar: "Santiago Bernabéu",
            resultadoA: "1",
            resultadoB: "0",
        },
        {
            status: "Encerrado",
            ladoA: "Bayern Munich",
            ladoB: "PSG",
            data: "08/03/2023",
            hora: "17:00",
            lugar: "Allianz Arena",
            resultadoA: "2",
            resultadoB: "0",
        },
        {
            status: "Encerrado",
            ladoA: "Chelsea",
            ladoB: "Borussia Dortmund",
            data: "07/03/2023",
            hora: "17:00",
            lugar: "Stamford Bridge",
            resultadoA: "2",
            resultadoB: "0",
        },
        {
            status: "Encerrado",
            ladoA: "Benfica",
            ladoB: "Club Brugge",
            data: "07/03/2023",
            hora: "17:00",
            lugar: "Estádio da Luz",
            resultadoA: "5",
            resultadoB: "1",
        },
        {
            status: "Encerrado",
            ladoA: "Milan",
            ladoB: "Tottenham",
            data: "14/02/2023",
            hora: "17:00",
            lugar: "San Siro",
            resultadoA: "1",
            resultadoB: "0",
        },
        {
            status: "Encerrado",
            ladoA: "Inter de Milão",
            ladoB: "Porto",
            data: "22/02/2023",
            hora: "17:00",
            lugar: "San Siro",
            resultadoA: "1",
            resultadoB: "0",
        },
        {
            status: "Encerrado",
            ladoA: "Napoli",
            ladoB: "Eintracht Frankfurt",
            data: "15/03/2023",
            hora: "17:00",
            lugar: "Diego Armando Maradona",
            resultadoA: "3",
            resultadoB: "0",
        },
        {
            status: "Encerrado",
            ladoA: "Barcelona",
            ladoB: "Bayern Munich",
            data: "26/10/2022",
            hora: "16:00",
            lugar: "Camp Nou",
            resultadoA: "0",
            resultadoB: "3",
        },
        {
            status: "Encerrado",
            ladoA: "Atletico Madrid",
            ladoB: "Porto",
            data: "07/09/2022",
            hora: "16:00",
            lugar: "Wanda Metropolitano",
            resultadoA: "2",
            resultadoB: "1",
        },
        {
            status: "Encerrado",
            ladoA: "Ajax",
            ladoB: "Napoli",
            data: "04/10/2022",
            hora: "16:00",
            lugar: "Johan Cruyff Arena",
            resultadoA: "1",
            resultadoB: "6",
        },
    ],
    participantes: [
        {
            nome: "Real Madrid",
            atletas: ["neyma"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "BarSemLona",
            atletas: ["neyma"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "FC Bayern München",
            atletas: ["neyma"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Arsenal",
            atletas: ["neyma"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Man. City",
            atletas: ["neyma"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Man. United ???",
            atletas: ["neyma"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "PSG",
            atletas: ["neyma"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Benfica",
            atletas: ["neyma"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
    ],
}

let Brasileirao = {
    id: 1,
    seguidores: 4700000,
    autor: "CBF - Confederação Brasileira de Futebol",
    nome: "Brasileirão - Série A",
    descricao: "A Liga dos Campeões da UEFA é uma competição anual de futebol em nível continental, organizada pela União das Associações Europeias de Futebol e disputada por clubes da Europa.",
    visibilidade: "Publico",
    esporte: "BRASILEIRAO",
    tipoCampeonato: "Liga",
    placarConfig: {
        qntSets: 1,
    },
    confrontos: [],
    participantes: [
        {
            nome: "Patético - MG",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Bahia",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Botafogo",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Bragantino",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Ceará",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Corinthians",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Cruzeiro",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Flamengo",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Fluminense",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Fortaleza",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Grêmio",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Internacional",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Juventude",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Mirassol",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Palmeiras",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Santos",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "São Paulo",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Sport",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Vasco da Gama",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
        {
            nome: "Vitória",
            atletas: ["atleta"],
            qntAtletas: 1,
            tipo: "Equipe de Atletas",
        },
    ]
}

if (!getTorneioById(0)) {
    addTorneioBASIC(Champions);
}

if (!getTorneioById(1)) {
    addTorneioBASIC(Brasileirao);
    gerarConfrontos(1, "com-rodadas", 'returno', "2025-03-15", 5, 3, "Brasil");
}
